# This file allows packrat (used by rsconnect during deployment) to pick up dependencies.

# Production
library(base64enc)
library(box)
library(checkmate)
library(countrycode)
library(data.table)
library(dplyr)
library(fst)
library(glue)
library(htmlwidgets)
library(leaflet)
library(logger)
library(magrittr)
library(plotly)
library(purrr)
library(rhino)
library(sf)
library(shiny)
library(shiny.semantic)
library(stringr)
library(waiter)
